// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: structs/structs/genesis.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AddressRecord } from "./address";
import { Agreement } from "./agreement";
import { Allocation } from "./allocation";
import { GridRecord } from "./grid";
import { Guild } from "./guild";
import { Infusion } from "./infusion";
import { Params } from "./params";
import { PermissionRecord } from "./permission";
import { Planet } from "./planet";
import { Player } from "./player";
import { Provider } from "./provider";
import { Reactor } from "./reactor";
import { Struct } from "./struct";
import { Substation } from "./substation";

export const protobufPackage = "structs.structs";

/** GenesisState defines the structs module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params: Params | undefined;
  portId: string;
  allocationList: Allocation[];
  agreementList: Agreement[];
  infusionList: Infusion[];
  guildList: Guild[];
  guildCount: number;
  planetList: Planet[];
  planetCount: number;
  playerList: Player[];
  playerHalted: string[];
  playerCount: number;
  providerList: Provider[];
  providerCount: number;
  reactorList: Reactor[];
  reactorCount: number;
  structList: Struct[];
  structCount: number;
  substationList: Substation[];
  substationCount: number;
  permissionList: PermissionRecord[];
  gridList: GridRecord[];
  addressList: AddressRecord[];
}

function createBaseGenesisState(): GenesisState {
  return {
    params: undefined,
    portId: "",
    allocationList: [],
    agreementList: [],
    infusionList: [],
    guildList: [],
    guildCount: 0,
    planetList: [],
    planetCount: 0,
    playerList: [],
    playerHalted: [],
    playerCount: 0,
    providerList: [],
    providerCount: 0,
    reactorList: [],
    reactorCount: 0,
    structList: [],
    structCount: 0,
    substationList: [],
    substationCount: 0,
    permissionList: [],
    gridList: [],
    addressList: [],
  };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    if (message.portId !== "") {
      writer.uint32(18).string(message.portId);
    }
    for (const v of message.allocationList) {
      Allocation.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.agreementList) {
      Agreement.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.infusionList) {
      Infusion.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.guildList) {
      Guild.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.guildCount !== 0) {
      writer.uint32(56).uint64(message.guildCount);
    }
    for (const v of message.planetList) {
      Planet.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.planetCount !== 0) {
      writer.uint32(72).uint64(message.planetCount);
    }
    for (const v of message.playerList) {
      Player.encode(v!, writer.uint32(82).fork()).join();
    }
    for (const v of message.playerHalted) {
      writer.uint32(90).string(v!);
    }
    if (message.playerCount !== 0) {
      writer.uint32(96).uint64(message.playerCount);
    }
    for (const v of message.providerList) {
      Provider.encode(v!, writer.uint32(106).fork()).join();
    }
    if (message.providerCount !== 0) {
      writer.uint32(112).uint64(message.providerCount);
    }
    for (const v of message.reactorList) {
      Reactor.encode(v!, writer.uint32(122).fork()).join();
    }
    if (message.reactorCount !== 0) {
      writer.uint32(128).uint64(message.reactorCount);
    }
    for (const v of message.structList) {
      Struct.encode(v!, writer.uint32(138).fork()).join();
    }
    if (message.structCount !== 0) {
      writer.uint32(144).uint64(message.structCount);
    }
    for (const v of message.substationList) {
      Substation.encode(v!, writer.uint32(154).fork()).join();
    }
    if (message.substationCount !== 0) {
      writer.uint32(160).uint64(message.substationCount);
    }
    for (const v of message.permissionList) {
      PermissionRecord.encode(v!, writer.uint32(170).fork()).join();
    }
    for (const v of message.gridList) {
      GridRecord.encode(v!, writer.uint32(178).fork()).join();
    }
    for (const v of message.addressList) {
      AddressRecord.encode(v!, writer.uint32(186).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.portId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.allocationList.push(Allocation.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.agreementList.push(Agreement.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.infusionList.push(Infusion.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.guildList.push(Guild.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.guildCount = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.planetList.push(Planet.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.planetCount = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.playerList.push(Player.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.playerHalted.push(reader.string());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.playerCount = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.providerList.push(Provider.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.providerCount = longToNumber(reader.uint64());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.reactorList.push(Reactor.decode(reader, reader.uint32()));
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.reactorCount = longToNumber(reader.uint64());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.structList.push(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.structCount = longToNumber(reader.uint64());
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.substationList.push(Substation.decode(reader, reader.uint32()));
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.substationCount = longToNumber(reader.uint64());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.permissionList.push(PermissionRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.gridList.push(GridRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.addressList.push(AddressRecord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      portId: isSet(object.portId) ? globalThis.String(object.portId) : "",
      allocationList: globalThis.Array.isArray(object?.allocationList)
        ? object.allocationList.map((e: any) => Allocation.fromJSON(e))
        : [],
      agreementList: globalThis.Array.isArray(object?.agreementList)
        ? object.agreementList.map((e: any) => Agreement.fromJSON(e))
        : [],
      infusionList: globalThis.Array.isArray(object?.infusionList)
        ? object.infusionList.map((e: any) => Infusion.fromJSON(e))
        : [],
      guildList: globalThis.Array.isArray(object?.guildList) ? object.guildList.map((e: any) => Guild.fromJSON(e)) : [],
      guildCount: isSet(object.guildCount) ? globalThis.Number(object.guildCount) : 0,
      planetList: globalThis.Array.isArray(object?.planetList)
        ? object.planetList.map((e: any) => Planet.fromJSON(e))
        : [],
      planetCount: isSet(object.planetCount) ? globalThis.Number(object.planetCount) : 0,
      playerList: globalThis.Array.isArray(object?.playerList)
        ? object.playerList.map((e: any) => Player.fromJSON(e))
        : [],
      playerHalted: globalThis.Array.isArray(object?.playerHalted)
        ? object.playerHalted.map((e: any) => globalThis.String(e))
        : [],
      playerCount: isSet(object.playerCount) ? globalThis.Number(object.playerCount) : 0,
      providerList: globalThis.Array.isArray(object?.providerList)
        ? object.providerList.map((e: any) => Provider.fromJSON(e))
        : [],
      providerCount: isSet(object.providerCount) ? globalThis.Number(object.providerCount) : 0,
      reactorList: globalThis.Array.isArray(object?.reactorList)
        ? object.reactorList.map((e: any) => Reactor.fromJSON(e))
        : [],
      reactorCount: isSet(object.reactorCount) ? globalThis.Number(object.reactorCount) : 0,
      structList: globalThis.Array.isArray(object?.structList)
        ? object.structList.map((e: any) => Struct.fromJSON(e))
        : [],
      structCount: isSet(object.structCount) ? globalThis.Number(object.structCount) : 0,
      substationList: globalThis.Array.isArray(object?.substationList)
        ? object.substationList.map((e: any) => Substation.fromJSON(e))
        : [],
      substationCount: isSet(object.substationCount) ? globalThis.Number(object.substationCount) : 0,
      permissionList: globalThis.Array.isArray(object?.permissionList)
        ? object.permissionList.map((e: any) => PermissionRecord.fromJSON(e))
        : [],
      gridList: globalThis.Array.isArray(object?.gridList)
        ? object.gridList.map((e: any) => GridRecord.fromJSON(e))
        : [],
      addressList: globalThis.Array.isArray(object?.addressList)
        ? object.addressList.map((e: any) => AddressRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.portId !== "") {
      obj.portId = message.portId;
    }
    if (message.allocationList?.length) {
      obj.allocationList = message.allocationList.map((e) => Allocation.toJSON(e));
    }
    if (message.agreementList?.length) {
      obj.agreementList = message.agreementList.map((e) => Agreement.toJSON(e));
    }
    if (message.infusionList?.length) {
      obj.infusionList = message.infusionList.map((e) => Infusion.toJSON(e));
    }
    if (message.guildList?.length) {
      obj.guildList = message.guildList.map((e) => Guild.toJSON(e));
    }
    if (message.guildCount !== 0) {
      obj.guildCount = Math.round(message.guildCount);
    }
    if (message.planetList?.length) {
      obj.planetList = message.planetList.map((e) => Planet.toJSON(e));
    }
    if (message.planetCount !== 0) {
      obj.planetCount = Math.round(message.planetCount);
    }
    if (message.playerList?.length) {
      obj.playerList = message.playerList.map((e) => Player.toJSON(e));
    }
    if (message.playerHalted?.length) {
      obj.playerHalted = message.playerHalted;
    }
    if (message.playerCount !== 0) {
      obj.playerCount = Math.round(message.playerCount);
    }
    if (message.providerList?.length) {
      obj.providerList = message.providerList.map((e) => Provider.toJSON(e));
    }
    if (message.providerCount !== 0) {
      obj.providerCount = Math.round(message.providerCount);
    }
    if (message.reactorList?.length) {
      obj.reactorList = message.reactorList.map((e) => Reactor.toJSON(e));
    }
    if (message.reactorCount !== 0) {
      obj.reactorCount = Math.round(message.reactorCount);
    }
    if (message.structList?.length) {
      obj.structList = message.structList.map((e) => Struct.toJSON(e));
    }
    if (message.structCount !== 0) {
      obj.structCount = Math.round(message.structCount);
    }
    if (message.substationList?.length) {
      obj.substationList = message.substationList.map((e) => Substation.toJSON(e));
    }
    if (message.substationCount !== 0) {
      obj.substationCount = Math.round(message.substationCount);
    }
    if (message.permissionList?.length) {
      obj.permissionList = message.permissionList.map((e) => PermissionRecord.toJSON(e));
    }
    if (message.gridList?.length) {
      obj.gridList = message.gridList.map((e) => GridRecord.toJSON(e));
    }
    if (message.addressList?.length) {
      obj.addressList = message.addressList.map((e) => AddressRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.portId = object.portId ?? "";
    message.allocationList = object.allocationList?.map((e) => Allocation.fromPartial(e)) || [];
    message.agreementList = object.agreementList?.map((e) => Agreement.fromPartial(e)) || [];
    message.infusionList = object.infusionList?.map((e) => Infusion.fromPartial(e)) || [];
    message.guildList = object.guildList?.map((e) => Guild.fromPartial(e)) || [];
    message.guildCount = object.guildCount ?? 0;
    message.planetList = object.planetList?.map((e) => Planet.fromPartial(e)) || [];
    message.planetCount = object.planetCount ?? 0;
    message.playerList = object.playerList?.map((e) => Player.fromPartial(e)) || [];
    message.playerHalted = object.playerHalted?.map((e) => e) || [];
    message.playerCount = object.playerCount ?? 0;
    message.providerList = object.providerList?.map((e) => Provider.fromPartial(e)) || [];
    message.providerCount = object.providerCount ?? 0;
    message.reactorList = object.reactorList?.map((e) => Reactor.fromPartial(e)) || [];
    message.reactorCount = object.reactorCount ?? 0;
    message.structList = object.structList?.map((e) => Struct.fromPartial(e)) || [];
    message.structCount = object.structCount ?? 0;
    message.substationList = object.substationList?.map((e) => Substation.fromPartial(e)) || [];
    message.substationCount = object.substationCount ?? 0;
    message.permissionList = object.permissionList?.map((e) => PermissionRecord.fromPartial(e)) || [];
    message.gridList = object.gridList?.map((e) => GridRecord.fromPartial(e)) || [];
    message.addressList = object.addressList?.map((e) => AddressRecord.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
