<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHCxHVtY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHCxHVtY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHCxHVtY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHCxHVtY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHCxHVtY\App_KernelDevDebugContainer([
    'container.build_hash' => 'HCxHVtY',
    'container.build_id' => '87f04ce6',
    'container.build_time' => 1733936423,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHCxHVtY');
