<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZA1eBIU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZA1eBIU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZA1eBIU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZA1eBIU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZA1eBIU\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZA1eBIU',
    'container.build_id' => '4ba78948',
    'container.build_time' => 1733861618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZA1eBIU');
