export const EVENTS = {
  CHARGE_LEVEL_CHANGED: 'CHARGE_LEVEL_CHANGED',
  ENERGY_USAGE_CHANGED: 'ENERGY_USAGE_CHANGED',
  ORE_COUNT_CHANGED: 'ORE_COUNT_CHANGED',
  SHIELD_HEALTH_CHANGED: 'SHIELD_HEALTH_CHANGED',
};