export const TASK = {
  WORKER_PATH: '/js/compute_worker-bundle.js',
  MAX_CONCURRENT_PROCESSES: 5,
  CHECKPOINT_COMMIT: 500000,
  CHECKPOINT_BLOCK: 10,
  IDENTITY_PREFIX: "IDENTITY",
  NONCE_PREFIX: "NONCE",
  TARGET_DELIMITER: "@",

};
