export const TASK = {
  WORKER_PATH: '/js/workers/TaskWorker.js',
  MAX_CONCURRENT_PROCESSES: 5,
  CHECKPOINT_COMMIT: 5000000,
  DIFFICULTY_RECALCULATE: 5000000,
  CHECKPOINT_BLOCK: 10,
  IDENTITY_PREFIX: "IDENTITY",
  NONCE_PREFIX: "NONCE",
  TARGET_DELIMITER: "@",

};
