<?php declare(strict_types=1);

namespace App\Tests\Oidc;

use App\Command\OidcGenerateKeyCommand;
use App\Oidc\OidcConfig;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Tester\CommandTester;

/**
 * The keypair is written by an operator running as root and read by the web
 * server running as someone else, so the file modes this command leaves behind
 * are part of its contract rather than an implementation detail.
 */
class OidcGenerateKeyCommandTest extends TestCase
{
    private string $directory;

    private CommandTester $tester;

    protected function setUp(): void
    {
        $this->directory = sys_get_temp_dir() . '/structs-oidc-keygen-' . bin2hex(random_bytes(6));

        $application = new Application();
        $application->addCommand(new OidcGenerateKeyCommand($this->buildConfig()));

        $this->tester = new CommandTester($application->find('app:oidc:generate-key'));
    }

    protected function tearDown(): void
    {
        foreach (['/private.key', '/public.key'] as $file) {
            if (file_exists($this->directory . $file)) {
                unlink($this->directory . $file);
            }
        }

        if (is_dir($this->directory)) {
            rmdir($this->directory);
        }
    }

    public function testItWritesAUsableKeypair(): void
    {
        self::assertSame(Command::SUCCESS, $this->tester->execute([]));

        $private = file_get_contents($this->directory . '/private.key');
        $public = file_get_contents($this->directory . '/public.key');

        self::assertNotFalse(openssl_pkey_get_private($private), 'Private key does not parse');
        self::assertNotFalse(openssl_pkey_get_public($public), 'Public key does not parse');
    }

    public function testThePrivateKeyIsNotWorldReadable(): void
    {
        $this->tester->execute([]);

        self::assertSame(0o640, $this->mode('/private.key'));
        self::assertSame(0o644, $this->mode('/public.key'));
    }

    /**
     * A key directory left at 0750 root:root is unreachable by the web server
     * whatever the key file itself says, so the directory is created group
     * traversable and handed over with the keys.
     */
    public function testTheKeyDirectoryIsTraversable(): void
    {
        $this->tester->execute([]);

        self::assertSame(0o750, $this->mode(''));
    }

    /**
     * The reported failure exactly: keys generated by root under Docker were
     * left as root:root 0600, and PHP-FPM answered /oauth/authorize with 500
     * because it could not read the key it was supposed to sign with.
     */
    public function testRootHandsTheKeypairToTheWebServerUser(): void
    {
        if (!function_exists('posix_geteuid') || posix_geteuid() !== 0) {
            self::markTestSkipped('Ownership is only transferable when running as root');
        }

        $webServer = posix_getpwnam('www-data');

        if ($webServer === false) {
            self::markTestSkipped('No www-data account on this host');
        }

        $this->tester->execute([]);

        foreach (['', '/private.key', '/public.key'] as $path) {
            clearstatcache(true, $this->directory . $path);
            self::assertSame(
                $webServer['uid'],
                fileowner($this->directory . $path),
                "www-data should own {$path}"
            );
        }

        self::assertStringContainsString('www-data', $this->tester->getDisplay());
    }

    public function testItReportsWhoCanReadTheKey(): void
    {
        $this->tester->execute([]);
        $display = $this->tester->getDisplay();

        self::assertStringContainsString('Readable by', $display);

        // Either it took ownership, or it said exactly how to finish the job.
        if (!str_contains($display, 'current user only')) {
            return;
        }

        self::assertStringContainsString('chown', $display);
        self::assertStringContainsString('is not readable', $display);
    }

    public function testAnUnknownOwnerIsReportedRatherThanSilentlySkipped(): void
    {
        self::assertSame(Command::SUCCESS, $this->tester->execute(['--owner' => 'nobody-by-this-name']));

        $display = $this->tester->getDisplay();

        self::assertStringContainsString('no nobody-by-this-name account', $display);
        self::assertStringContainsString('chown', $display);
    }

    /**
     * Replacing the key invalidates every live Matrix session, so it must not
     * be something a re-run of a deploy script does by accident.
     */
    public function testItRefusesToOverwriteWithoutForce(): void
    {
        $this->tester->execute([]);
        $original = file_get_contents($this->directory . '/private.key');

        self::assertSame(Command::FAILURE, $this->tester->execute([]));
        self::assertSame($original, file_get_contents($this->directory . '/private.key'));

        self::assertSame(Command::SUCCESS, $this->tester->execute(['--force' => true]));
        self::assertNotSame($original, file_get_contents($this->directory . '/private.key'));
    }

    private function mode(string $file): int
    {
        clearstatcache(true, $this->directory . $file);

        return fileperms($this->directory . $file) & 0o777;
    }

    private function buildConfig(): OidcConfig
    {
        return new OidcConfig(
            true,
            'https://guild.test.structs.game',
            'matrix-auth-service',
            'client-secret',
            'https://auth.test.structs.game/upstream/callback/01',
            $this->directory . '/private.key',
            $this->directory . '/public.key',
            'test-key-1',
            'a-thirty-two-byte-test-encryption',
            $this->directory
        );
    }
}
